// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VayaPreguntita.API.Data;

#nullable disable

namespace VayaPreguntita.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006210927_AddMemberStreaks")]
    partial class AddMemberStreaks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VayaPreguntita.API.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyEntryId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DailyEntryId", "UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.DailyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAutoSelected")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PreselectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SelectorReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SelectorUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectorUserId");

                    b.HasIndex("GroupId", "Date")
                        .IsUnique();

                    b.ToTable("DailyEntries");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.DevicePushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DevicePushSubscriptions");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("DailyQuestionTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultPacksApplied")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.GroupDisabledPack", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("PackId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "PackId");

                    b.HasIndex("PackId");

                    b.ToTable("GroupDisabledPacks");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastStreakEntryId")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationsMuted")
                        .HasColumnType("boolean");

                    b.Property<int?>("StreakDangerNotifiedEntryId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.NotificationPreferences", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("NewMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("NewQuestion")
                        .HasColumnType("boolean");

                    b.Property<bool>("SelectorTurn")
                        .HasColumnType("boolean");

                    b.Property<bool>("StreakDanger")
                        .HasColumnType("boolean");

                    b.Property<int>("StreakDangerHoursBefore")
                        .HasColumnType("integer");

                    b.Property<bool>("UserVoted")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Pack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DisabledByDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActiveByDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateActivated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.QuestionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PackId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.ToTable("QuestionTemplates");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.QuestionTemplateOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTemplateId");

                    b.ToTable("QuestionTemplateOption");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrameColor")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StreakFrameAutoApplied")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.UserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateResponded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FreeText")
                        .HasColumnType("text");

                    b.Property<int?>("NumericValue")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedTargetUserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("SelectedTargetUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("QuestionId", "UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.ChatMessage", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.DailyEntry", "DailyEntry")
                        .WithMany()
                        .HasForeignKey("DailyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VayaPreguntita.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.DailyEntry", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.Group", "Group")
                        .WithMany("DailyEntries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VayaPreguntita.API.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VayaPreguntita.API.Entities.User", "Selector")
                        .WithMany()
                        .HasForeignKey("SelectorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Question");

                    b.Navigation("Selector");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.DevicePushSubscription", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Group", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.User", "Creator")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.GroupDisabledPack", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VayaPreguntita.API.Entities.Pack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.GroupMember", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VayaPreguntita.API.Entities.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.NotificationPreferences", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("VayaPreguntita.API.Entities.NotificationPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Option", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Question", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.User", "Creator")
                        .WithMany("CreatedQuestions")
                        .HasForeignKey("CreatorId");

                    b.HasOne("VayaPreguntita.API.Entities.Group", "Group")
                        .WithMany("Questions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VayaPreguntita.API.Entities.QuestionTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("VayaPreguntita.API.Entities.QuestionMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("QuestionId");

                            b1.Property<bool>("AllowNobody");

                            b1.Property<bool>("AllowOther");

                            b1.PrimitiveCollection<string>("BlacklistedUserIds")
                                .IsRequired();

                            b1.Property<int>("MaxSelections");

                            b1.Property<int>("MinSelections");

                            b1.Property<int?>("RangeMax");

                            b1.Property<int?>("RangeMin");

                            b1.Property<int?>("TargetUserId");

                            b1.Property<string>("Teams")
                                .IsRequired();

                            b1.HasKey("QuestionId");

                            b1.ToTable("Questions");

                            b1
                                .ToJson("Metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.Navigation("Creator");

                    b.Navigation("Group");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.QuestionTemplate", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.Pack", "Pack")
                        .WithMany("Templates")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VayaPreguntita.API.Entities.QuestionMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("QuestionTemplateId");

                            b1.Property<bool>("AllowNobody");

                            b1.Property<bool>("AllowOther");

                            b1.PrimitiveCollection<string>("BlacklistedUserIds")
                                .IsRequired();

                            b1.Property<int>("MaxSelections");

                            b1.Property<int>("MinSelections");

                            b1.Property<int?>("RangeMax");

                            b1.Property<int?>("RangeMin");

                            b1.Property<int?>("TargetUserId");

                            b1.Property<string>("Teams")
                                .IsRequired();

                            b1.HasKey("QuestionTemplateId");

                            b1.ToTable("QuestionTemplates");

                            b1
                                .ToJson("Metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QuestionTemplateId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.QuestionTemplateOption", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.QuestionTemplate", "QuestionTemplate")
                        .WithMany("Options")
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionTemplate");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Vote", b =>
                {
                    b.HasOne("VayaPreguntita.API.Entities.Question", "Question")
                        .WithMany("Votes")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VayaPreguntita.API.Entities.Option", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId");

                    b.HasOne("VayaPreguntita.API.Entities.User", "SelectedTargetUser")
                        .WithMany()
                        .HasForeignKey("SelectedTargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VayaPreguntita.API.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("SelectedTargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Group", b =>
                {
                    b.Navigation("DailyEntries");

                    b.Navigation("Members");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Pack", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.Question", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.QuestionTemplate", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("VayaPreguntita.API.Entities.User", b =>
                {
                    b.Navigation("CreatedGroups");

                    b.Navigation("CreatedQuestions");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
